[package]
name = "pods"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
reqwest = "0.11.18"
roxmltree = "0.18.0"
serde = { version = "1.0.166", features = ["serde_derive"] }
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.4.0", features = ["serde", "v4"] }
